### ISSUE TITLE
Finetuning vit_b_lm, CUDA out of memory issue

### ISSUE THREAD

**Issue by z-pan** [computational-cell-analytics/micro-sam#1038]
Hi, 

I am trying to finetune vit_b_lm model, with 900+ 256*256 paired data. 
Hardware:
- Nvidia RTX 3080, with VRAM = **10 GB**
Parameters (the ones I assume related to VRAM usage, from issue#1015):
- n_objects_per_batch = 1
- patch_shape (1, 256, 256)

I am getting CUDA out of memory issue. Though it works when finetuning **vit_t_lm**, I still want to try with **vit_b_lm** for better performance. 

There are actually **two** Nvidia RTX 3080 on my machine, is there a way to make use of both GPUs to solve this issue?

Thank you!

**Comment by anwai98** [comment]
Hi @z-pan,

> Nvidia RTX 3080, with VRAM = 10 GB

The hardware details you've provided are not enough to finetune `micro-sam` with the `vit_b` model configuration! (there's quite a lot of parameters, and the lowest it drops down for full finetuning is ca. 12GB, with your patch shape and `n_objects_per_batch` set to 1 - I briefly checked it just now)

> I still want to try with vit_b_lm for better performance.

Unfortunately, this won't be possible in your current GPU setting, without trying out parameter efficient finetuning (we do support them in `micro-sam` and there's a lot of choices there (see our [work](https://github.com/computational-cell-analytics/peft-sam) on this to build better PEFT methods for SAM)

> There are actually two Nvidia RTX 3080 on my machine, is there a way to make use of both GPUs to solve this issue?

You can use multiple GPUs for distribted data parallel training (we recently integrated it: https://github.com/computational-cell-analytics/micro-sam/pull/991, in the `dev` branch, and will make a release in the coming weeks), but I doubt that would aid the memory footprint issue you are facing right now!

There are only a few suggestions I can give here:
- Stick to finetuning `vit_t` model variants and experiment with it on your data.
- Finetune `vit_b` model variants on your data by a) getting hands on a GPU with bigger VRAM (~16GB often does the trick), b) freezing different parts of the network for your data, or c) look into PEFT methods offered by `micro-sam` (https://github.com/computational-cell-analytics/peft-sam)
- Look for some openly available cloud platforms for training purpose, eg. [Kaggle Notebooks](https://www.kaggle.com/code) offers free access to 16GB VRAM GPUs. Use their offered GPUs for training purpose!

Hope this helps!
